### ISSUE TITLE
Exceeding "max_tries" throws "Fatal undefined"

### ISSUE THREAD

**Issue by tomaskikutis** [demmer/bluebird-retry#26]
I was using [Request](https://www.npmjs.com/package/request) to scrap some pages and started getting "Fatal undefined" errors. After A WHILE I figured what's happening and was able to reproduce the problem by minimally altering the code in your example:

```
var Promise = require('bluebird');
var retry = require('bluebird-retry');

var count = 0;
function myfunc() {
    console.log('myfunc called ' + (++count) + ' times');
    if (count < 10) {
        return Promise.reject(10);
    } else {
        return Promise.resolve('succeed the third time');
    }
}

retry(myfunc).done(function(result) {
    console.log(result);
});
```

[view diff](https://www.diffchecker.com/6keqeudg)

console output:

```
C:\my-project-folder>node script.js
myfunc called 1 times
myfunc called 2 times
myfunc called 3 times
myfunc called 4 times
myfunc called 5 times
Fatal undefined

C:\my-project-folder>
```

You should consider displaying error message which is easier to understand like "Fatal: You have exceeded maximum number of retries which is 5. You can alter 'max_tries' option if you want to retry more times".

**Comment by demmer** [comment]
@tomaskikutis The problem here was that if the called function rejects with a non-Error, the timeout logic didn't properly format an error to return.

I fixed this in #29 so your example now results in:
```
myfunc called 1 times
myfunc called 2 times
myfunc called 3 times
myfunc called 4 times
myfunc called 5 times
Fatal Error: operation timed out after 4012 ms, 5 tries with error: rejected with non-error: 10
    at /Users/demmer/work/bluebird-retry/lib/bluebird-retry.js:95:35
    at tryCatcher (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/catch_filter.js:24:41
    at tryCatcher (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/promise.js:503:31)
    at Promise._settlePromise (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/promise.js:560:18)
    at Promise._settlePromise0 (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/promise.js:605:10)
    at Promise._settlePromises (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/promise.js:680:18)
    at Async._drainQueue (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/async.js:126:16)
    at Async._drainQueues (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/async.js:136:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/demmer/work/bluebird-retry/node_modules/bluebird/js/release/async.js:16:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

This fix has been included in the 0.7.0 release I just published.
